// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import <Foundation/Foundation.h>
@class HWDehaze;


@interface HWDehaze : NSObject

+ (nullable HWDehaze *)create;

- (nonnull NSString *)dehaze:(nonnull NSString *)uri
                       media:(nonnull NSString *)media;

@end
