// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import <Foundation/Foundation.h>
@class HWHelloWorld;


@interface HWHelloWorld : NSObject

+ (nullable HWHelloWorld *)create;

- (nonnull NSString *)getHelloWorld;

- (int32_t)add:(int32_t)a
             b:(int32_t)b;

@end
